// @ts-nocheck
import { Express } from "express";

export function registerMfgInventoryRoutes(app: Express) {
    const tid = (req: any) => req.user?.tenantId || req.query?.tenantId || "default-tenant";

    // ─── ECO ─────────────────────────────────────────────────────────────────
    app.post("/api/mfg/eco", async (req, res) => { try { const { ecoService: s } = await import("./eco-and-ops.service"); res.status(201).json(await s.createECO({ ...req.body, tenantId: tid(req) })); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.post("/api/mfg/eco/:id/action", async (req, res) => { try { const { ecoService: s } = await import("./eco-and-ops.service"); res.json(await s.advance(req.params.id, req.body.action, req.body.actor, req.body.comments)); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/eco", async (req, res) => { try { const { ecoService: s } = await import("./eco-and-ops.service"); res.json(await s.list(tid(req), req.query.status as string, req.query.priority as string)); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/eco/summary", async (req, res) => { try { const { ecoService: s } = await import("./eco-and-ops.service"); res.json(await s.getSummary(tid(req))); } catch (e: any) { res.status(500).json({ error: e.message }); } });

    // ─── Outside Processing ───────────────────────────────────────────────────
    app.post("/api/mfg/outside-processing", async (req, res) => { try { const { outsideProcessingService: s } = await import("./eco-and-ops.service"); res.status(201).json(await s.createOp({ ...req.body, tenantId: tid(req) })); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.post("/api/mfg/outside-processing/:id/receive", async (req, res) => { try { const { outsideProcessingService: s } = await import("./eco-and-ops.service"); res.json(await s.receiveBack(req.params.id, req.body.qtyReceived, req.body.actualCost, req.body.qualityResult, req.body.notes)); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/outside-processing", async (req, res) => { try { const { outsideProcessingService: s } = await import("./eco-and-ops.service"); res.json(await s.list(tid(req), req.query.workOrderId as string, req.query.status as string)); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/outside-processing/variance", async (req, res) => { try { const { outsideProcessingService: s } = await import("./eco-and-ops.service"); res.json(await s.getVarianceReport(tid(req))); } catch (e: any) { res.status(500).json({ error: e.message }); } });

    // ─── Capacity Planning ────────────────────────────────────────────────────
    app.post("/api/mfg/capacity", async (req, res) => { try { const { capacityPlanningService: s } = await import("./eco-and-ops.service"); res.json(await s.upsertCapacity({ ...req.body, tenantId: tid(req) })); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/capacity/utilization", async (req, res) => { try { const { capacityPlanningService: s } = await import("./eco-and-ops.service"); res.json(await s.getUtilization(tid(req), req.query.from as string, req.query.to as string, req.query.workCenter as string)); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/capacity/bottlenecks", async (req, res) => { try { const { capacityPlanningService: s } = await import("./eco-and-ops.service"); res.json(await s.getBottlenecks(tid(req), req.query.from as string, req.query.to as string)); } catch (e: any) { res.status(500).json({ error: e.message }); } });

    // ─── WIP Costing ─────────────────────────────────────────────────────────
    app.post("/api/mfg/wip/transactions", async (req, res) => { try { const { wipCostingService: s } = await import("./eco-and-ops.service"); res.status(201).json(await s.postTransaction({ ...req.body, tenantId: tid(req) })); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.post("/api/mfg/wip/transactions/:id/reverse", async (req, res) => { try { const { wipCostingService: s } = await import("./eco-and-ops.service"); res.json(await s.reverseTransaction(req.params.id, tid(req))); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/wip/work-orders/:id/cost", async (req, res) => { try { const { wipCostingService: s } = await import("./eco-and-ops.service"); res.json(await s.getWorkOrderCost(tid(req), req.params.id)); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/wip/summary", async (req, res) => { try { const { wipCostingService: s } = await import("./eco-and-ops.service"); res.json(await s.getWIPSummary(tid(req))); } catch (e: any) { res.status(500).json({ error: e.message }); } });

    // ─── Lot Genealogy ────────────────────────────────────────────────────────
    app.post("/api/mfg/lots", async (req, res) => { try { const { lotGenealogyService: s } = await import("./inventory-ops.service"); res.status(201).json(await s.createLot({ ...req.body, tenantId: tid(req) })); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.post("/api/mfg/lots/:lot/trace-event", async (req, res) => { try { const { lotGenealogyService: s } = await import("./inventory-ops.service"); res.json(await s.addTraceEvent(req.params.lot, tid(req), req.body)); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.post("/api/mfg/lots/:lot/status", async (req, res) => { try { const { lotGenealogyService: s } = await import("./inventory-ops.service"); res.json(await s.updateStatus(req.params.lot, tid(req), req.body.status)); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/lots", async (req, res) => { try { const { lotGenealogyService: s } = await import("./inventory-ops.service"); res.json(await s.list(tid(req), req.query.item as string, req.query.status as string, req.query.type as string)); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/lots/:lot", async (req, res) => { try { const { lotGenealogyService: s } = await import("./inventory-ops.service"); res.json(await s.getLot(req.params.lot, tid(req))); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/lots/:lot/trace-up", async (req, res) => { try { const { lotGenealogyService: s } = await import("./inventory-ops.service"); res.json(await s.traceUp(req.params.lot, tid(req))); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/lots/:lot/trace-down", async (req, res) => { try { const { lotGenealogyService: s } = await import("./inventory-ops.service"); res.json(await s.traceDown(req.params.lot, tid(req))); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/lots/expiring", async (req, res) => { try { const { lotGenealogyService: s } = await import("./inventory-ops.service"); res.json(await s.getExpiringLots(tid(req), Number(req.query.days ?? 30))); } catch (e: any) { res.status(500).json({ error: e.message }); } });

    // ─── Quality Hold ─────────────────────────────────────────────────────────
    app.post("/api/mfg/quality-holds", async (req, res) => { try { const { qualityHoldService: s } = await import("./inventory-ops.service"); res.status(201).json(await s.initiateHold({ ...req.body, tenantId: tid(req) })); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.post("/api/mfg/quality-holds/:id/review", async (req, res) => { try { const { qualityHoldService: s } = await import("./inventory-ops.service"); res.json(await s.review(req.params.id, req.body.reviewedBy, req.body.rootCause)); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.post("/api/mfg/quality-holds/:id/dispose", async (req, res) => { try { const { qualityHoldService: s } = await import("./inventory-ops.service"); res.json(await s.dispose(req.params.id, req.body.approvedBy, req.body.disposition, req.body.notes)); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/quality-holds", async (req, res) => { try { const { qualityHoldService: s } = await import("./inventory-ops.service"); res.json(await s.list(tid(req), req.query.status as string, req.query.severity as string)); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/quality-holds/summary", async (req, res) => { try { const { qualityHoldService: s } = await import("./inventory-ops.service"); res.json(await s.getSummary(tid(req))); } catch (e: any) { res.status(500).json({ error: e.message }); } });

    // ─── Physical Inventory ───────────────────────────────────────────────────
    app.post("/api/mfg/physical-inventory/cycles", async (req, res) => { try { const { physicalInventoryService: s } = await import("./inventory-ops.service"); res.status(201).json(await s.createCycle({ ...req.body, tenantId: tid(req) })); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.post("/api/mfg/physical-inventory/cycles/:id/lines", async (req, res) => { try { const { physicalInventoryService: s } = await import("./inventory-ops.service"); res.json(await s.addLines(req.params.id, tid(req), req.body.lines)); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.post("/api/mfg/physical-inventory/lines/:id/count", async (req, res) => { try { const { physicalInventoryService: s } = await import("./inventory-ops.service"); res.json(await s.recordCount(req.params.id, req.body.countQuantity, req.body.countedBy)); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.post("/api/mfg/physical-inventory/cycles/:id/approve", async (req, res) => { try { const { physicalInventoryService: s } = await import("./inventory-ops.service"); res.json(await s.approveCycle(req.params.id, req.body.approvedBy)); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/physical-inventory/cycles", async (req, res) => { try { const { physicalInventoryService: s } = await import("./inventory-ops.service"); res.json(await s.listCycles(tid(req), req.query.status as string)); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/physical-inventory/cycles/:id/variance", async (req, res) => { try { const { physicalInventoryService: s } = await import("./inventory-ops.service"); res.json(await s.getVarianceSummary(req.params.id)); } catch (e: any) { res.status(500).json({ error: e.message }); } });

    // ─── Consignment ──────────────────────────────────────────────────────────
    app.post("/api/mfg/consignment", async (req, res) => { try { const { consignmentService: s } = await import("./inventory-ops.service"); res.status(201).json(await s.upsertRecord({ ...req.body, tenantId: tid(req) })); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.post("/api/mfg/consignment/:id/consume", async (req, res) => { try { const { consignmentService: s } = await import("./inventory-ops.service"); res.json(await s.recordConsumption(req.params.id, req.body.qtyConsumed)); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.post("/api/mfg/consignment/:id/replenish", async (req, res) => { try { const { consignmentService: s } = await import("./inventory-ops.service"); res.json(await s.replenish(req.params.id, req.body.qtyAdded)); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/consignment", async (req, res) => { try { const { consignmentService: s } = await import("./inventory-ops.service"); res.json(await s.list(tid(req), req.query.type as string, req.query.status as string)); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/consignment/alerts", async (req, res) => { try { const { consignmentService: s } = await import("./inventory-ops.service"); res.json(await s.getReplenishmentAlerts(tid(req))); } catch (e: any) { res.status(500).json({ error: e.message }); } });
    app.get("/api/mfg/consignment/summary", async (req, res) => { try { const { consignmentService: s } = await import("./inventory-ops.service"); res.json(await s.getConsumptionSummary(tid(req))); } catch (e: any) { res.status(500).json({ error: e.message }); } });
}
