import {
    FileText,
    DollarSign,
    BarChart3,
    TrendingUp,
    Briefcase,
    Settings,
    Layers,
    CheckSquare,
    RefreshCw,
    ShieldCheck,
    FileCheck,
    PieChart,
    RotateCcw,
    BookOpen,
    AlertCircle,
    ArrowRight,
    Upload,
    GitBranch,
    Search,
    Shield,
    Wallet,
    Banknote,
    MapPin,
    Plus,
    TrendingDown,
    Building2,
    Settings2,
} from "lucide-react";
import { DomainSidebar } from "./DomainSidebar";

export const financeMenu = [
    {
        label: "General Ledger",
        items: [
            { title: "Dashboard", url: "/finance", icon: BarChart3 },
            { title: "Journals", url: "/finance/gl/journals", icon: FileText },
            { title: "Trial Balance", url: "/finance/gl/trial-balance", icon: BarChart3 },
            { title: "Consolidation", url: "/finance/gl/consolidation", icon: Layers },
            { title: "Close Center", url: "/finance/gl/close-center", icon: CheckSquare },
            { title: "Chart of Accounts", url: "/finance/gl/coa-structures", icon: Settings },
            { title: "Configuration Hub", url: "/finance/gl/config", icon: Settings },
            { title: "Accounting Calendars", url: "/finance/gl/config/calendars", icon: Settings },
            { title: "Value Sets", url: "/finance/gl/value-sets", icon: Settings },
        ],
    },
    {
        label: "Payables (AP)",
        items: [
            { title: "AP Dashboard", url: "/finance/ap", icon: BarChart3 },
            { title: "Invoice Workbench", url: "/finance/ap/invoices", icon: FileText },
            { title: "Suppliers", url: "/finance/ap/suppliers", icon: Users },
            { title: "Payment Batches", url: "/finance/ap/payments", icon: DollarSign },
            { title: "Prepayments", url: "/finance/ap/prepayments", icon: DollarSign },
            { title: "AI Invoice Capture", url: "/finance/ap/ai-capture", icon: TrendingUp },
            { title: "Reports", url: "/finance/ap/reports", icon: BarChart3 },
            { title: "Withholding Tax", url: "/finance/ap/withholding-tax", icon: Settings },
            { title: "Recurring Invoices", url: "/finance/ap/recurring-invoices", icon: RefreshCw },
            { title: "Supplier Merge", url: "/finance/ap/supplier-merge", icon: RefreshCw },
            { title: "Hold Types Setup", url: "/finance/ap/config/hold-types", icon: Settings },
            { title: "Distribution Sets", url: "/finance/ap/config/distribution-sets", icon: FileText },
            { title: "4-Way Match Config", url: "/finance/ap/config/match-tolerances", icon: CheckSquare },
            { title: "Positive Pay", url: "/finance/ap/positive-pay", icon: Shield },
            { title: "Configuration", url: "/finance/ap/config", icon: Settings },
        ],
    },
    {
        label: "Receivables (AR)",
        items: [
            { title: "Dunning Workbench", url: "/finance/ar/dunning", icon: FileCheck },
            { title: "Invoices", url: "/finance/ar/invoices", icon: FileText },
            { title: "Statement of Account", url: "/finance/ar/statements", icon: FileText },
            { title: "Remittance Batches", url: "/finance/ar/remittance-batches", icon: CheckSquare },
            { title: "Customer Hierarchy", url: "/finance/ar/customer-hierarchy", icon: Users },
            { title: "Lockbox Setup", url: "/finance/ar/lockbox-setup", icon: Settings2 },
            { title: "Chargeback Workbench", url: "/finance/ar/chargebacks", icon: RotateCcw },
            { title: "Credit / Debit Memos", url: "/finance/ar/credit-debit-memos", icon: FileText },
            { title: "Receipt Application", url: "/finance/ar/receipt-application", icon: CheckSquare },
            { title: "Adjustment Approvals", url: "/finance/ar/adjustment-approvals", icon: ShieldCheck },
            { title: "Analytics", url: "/finance/ar/analytics", icon: BarChart3 },
            { title: "Reports", url: "/finance/ar/reports", icon: FileText },
            { title: "Period Close", url: "/finance/ar/period-close", icon: CheckSquare },
        ],
    },
    {
        label: "Billing & Revenue",
        items: [
            { title: "Billing Dashboard", url: "/finance/billing", icon: BarChart3 },
            { title: "Billing Workbench", url: "/finance/billing/workbench", icon: FileText },
            { title: "Revenue Contracts", url: "/finance/revenue/contracts", icon: DollarSign },
            { title: "TAX Management", url: "/finance/tax", icon: DollarSign },
            { title: "VAT Return Wizard", url: "/finance/tax/vat-return", icon: FileText },
            { title: "Tax Subscriptions", url: "/finance/tax/subscriptions", icon: Shield },
            { title: "Supplier TRN Validator", url: "/finance/tax/supplier-trn", icon: Search },
            { title: "Expense Management", url: "/finance/expense-management", icon: FileText },
            { title: "New Expense Report", url: "/expenses/new-report", icon: Plus },
            { title: "Expense Approvals", url: "/expenses/approvals", icon: CheckSquare },
            { title: "Cash Advances", url: "/expenses/cash-advances", icon: Wallet },
            { title: "Audit Rule Sets", url: "/expenses/audit-rules", icon: Shield },
            { title: "Payroll Reimbursement", url: "/expenses/payroll-reimbursement", icon: Banknote },
            { title: "Per Diem Rates", url: "/expenses/per-diem-rates", icon: MapPin },
        ],
    },
    {
        label: "Assets & Cash",
        items: [
            { title: "Asset Workbench", url: "/finance/fixed-assets", icon: Briefcase },
            { title: "Fixed Assets", url: "/finance/fixed-assets/inquiry", icon: FileText },
            { title: "Add Asset", url: "/finance/fixed-assets/add-asset", icon: Plus },
            { title: "Capital Projects (CIP)", url: "/finance/fixed-assets/capital-projects", icon: TrendingUp },
            { title: "Tax Books (MACRS)", url: "/finance/fixed-assets/tax-books", icon: BookOpen },
            { title: "Reclassification", url: "/finance/fixed-assets/reclassification", icon: ArrowRight },
            { title: "Mass Additions", url: "/finance/fixed-assets/mass-additions", icon: Layers },
            { title: "Group Assets", url: "/finance/fixed-assets/group-assets", icon: Layers },
            { title: "Mass Change", url: "/finance/fixed-assets/mass-change", icon: RefreshCw },
            { title: "What-If Analysis", url: "/finance/fixed-assets/what-if", icon: BarChart3 },
            { title: "Depreciation Projection", url: "/finance/fixed-assets/depreciation-projection", icon: TrendingDown },
            { title: "Impairment Testing", url: "/finance/fixed-assets/impairment", icon: AlertCircle },
            { title: "Prorate Conventions", url: "/finance/fixed-assets/prorate-conventions", icon: Settings },
            { title: "Physical Inventory", url: "/finance/fixed-assets/physical-inventory", icon: CheckSquare },
            { title: "Bank Setup", url: "/finance/cash/bank-accounts", icon: Building2 },
            { title: "Statement Match Rules", url: "/finance/cash/match-rules", icon: Settings2 },
            { title: "CAMT.054 Import", url: "/finance/cash/camt-import", icon: Upload },
            { title: "Treasury Bank Accounts", url: "/finance/treasury/bank-accounts", icon: Briefcase },
            { title: "Cash Dashboard", url: "/finance/cash", icon: BarChart3 },
            { title: "Bank Statement Import", url: "/finance/cash/bank-statement-import", icon: Upload },
            { title: "Bank Reconciliation", url: "/finance/cash/reconciliation", icon: CheckSquare },
            { title: "Cash Forecasting", url: "/finance/cash/forecasting", icon: TrendingUp },
            { title: "Currency Revaluation", url: "/finance/cash/revaluation", icon: RefreshCw },
            { title: "Notional Cash Pooling", url: "/finance/cash/notional-pooling", icon: Layers },
            { title: "Bank Exceptions", url: "/finance/cash/bank-exceptions", icon: AlertCircle },
            { title: "ZBA Management", url: "/finance/cash/zba", icon: Layers },
        ],
    },
    {
        label: "Intercompany",
        items: [
            { title: "IC Dashboard", url: "/finance/intercompany", icon: TrendingUp },
            { title: "Workbench", url: "/finance/intercompany/workbench", icon: TrendingUp },
            { title: "Reconciliation", url: "/finance/intercompany/reconciliation", icon: BarChart3 },
            { title: "Netting", url: "/finance/intercompany/netting", icon: TrendingUp },
            { title: "Netting Settlement", url: "/finance/intercompany/netting-settlement", icon: DollarSign },
            { title: "Auto-Invoice", url: "/finance/intercompany/auto-invoice", icon: FileText },
            { title: "Receiver Workbench", url: "/finance/intercompany/receiver-workbench", icon: CheckSquare },
            { title: "IC Disputes", url: "/finance/ic/disputes", icon: FileText },
        ],
    },
    {
        label: "Lease Management",
        items: [
            { title: "Portfolio Workbench", url: "/finance/leases", icon: Briefcase },
            { title: "Subleases", url: "/finance/leases/subleases", icon: Building2 },
            { title: "Initial Direct Costs", url: "/finance/leases/initial-direct-costs", icon: DollarSign },
            { title: "Compliance Dashboard", url: "/finance/leases/compliance", icon: PieChart },
            { title: "Approval Hub", url: "/finance/leases/approvals", icon: FileCheck },
            { title: "Approval Chains", url: "/finance/leases/approval-chains", icon: GitBranch },
            { title: "Lease System Setup", url: "/finance/leases/setup", icon: Settings },
            { title: "Disclosure Reports", url: "/finance/leases/reports/disclosure", icon: FileText },
        ]
    },
    {
        label: "Enterprise Performance (EPM)",
        items: [
            { title: "Smart View", url: "/finance/epm/smartview", icon: Layers },
            { title: "Strategic Modeling", url: "/epm/strategic-modeling", icon: TrendingUp },
            { title: "CapEx Planning", url: "/epm/capex-planning", icon: Briefcase },
            { title: "Budget Control Rules", url: "/finance/epm/budget-controls", icon: CheckSquare },
            { title: "Variance Analysis", url: "/finance/epm/variance-analysis", icon: BarChart3 },
            { title: "Scenario Comparison", url: "/finance/epm/scenarios", icon: Layers },
            { title: "ESG & Sustainability", url: "/epm/esg", icon: TrendingUp },
            { title: "ESG Supplier Surveys", url: "/finance/epm/esg/supplier-surveys", icon: CheckSquare },
            { title: "ESG Public Dashboard", url: "/finance/epm/esg/public-dashboard", icon: BarChart3 },
        ]
    },
    {
        label: "Contracts (CLM)",
        items: [
            { title: "Contract List", url: "/finance/contracts", icon: FileText },
        ]
    },
    {
        label: "Reporting",
        items: [
            { title: "Financial Reports", url: "/finance/gl/reports", icon: BarChart3 },
            { title: "Report Builder", url: "/finance/gl/reports/builder", icon: Settings },
        ],
    },
];

// Import missing icons locally for now if not available in lucide-react (Clock/Users were implied)
import { Clock, Users } from "lucide-react";

export function FinanceSidebar() {
    return <DomainSidebar title="Finance" menu={financeMenu} />;
}
